### PR TITLE
WIP WebGL로 변경중 - merge 금지

### PR DESCRIPTION
**Pull request by shawnmypark**

### CODE REVIEW

**Comment by entrydev** [comment]
SonarQube analysis reported 62 issues
* ![MAJOR][MAJOR] 58 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 3 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [PIXIHelper.js#L38](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/PIXIHelper.js#L38): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L29](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L29): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L33](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L33): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L36](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L36): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L43](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L43): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L321](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L321): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L342](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L342): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L855](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L855): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L857](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L857): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L864](https://github.com/entrylabs/entryjs/blob/4d531ec46bd4b77a60a231f48bf34e0f221fb74a/src/class/entity.js#L864): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by entrydev** [comment]
SonarQube analysis reported 62 issues
* ![MAJOR][MAJOR] 58 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 3 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [PIXIHelper.js#L38](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/PIXIHelper.js#L38): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L29](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L29): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L33](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L33): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L36](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L36): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L43](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L43): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L321](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L321): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L342](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L342): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L855](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L855): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L857](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L857): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L864](https://github.com/entrylabs/entryjs/blob/b279f8a98135ca9827dcf25f3edc74537240fddb/src/class/entity.js#L864): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by entrydev** [comment]
SonarQube analysis reported 62 issues
* ![MAJOR][MAJOR] 58 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 3 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [PIXIHelper.js#L38](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/PIXIHelper.js#L38): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L29](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L29): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L33](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L33): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L36](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L36): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L43](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L43): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L321](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L321): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L342](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L342): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L855](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L855): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L857](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L857): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)
1. ![MAJOR][MAJOR] [entity.js#L864](https://github.com/entrylabs/entryjs/blob/386ffd446ce6c5a09048927acc2e5c3045fae47d/src/class/entity.js#L864): Remove this commented out code. [rule](http://10.106.152.77:9000/coding_rules#rule_key=javascript%3ACommentedCode)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by shawnmypark** [comment]
WebGL 예전 PR은 닫습니다.

**Pull request closed without merging**
